services:
  - type: web
    name: dojorobot-7seg-display
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
